# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyDemonClicker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyDemonClicker
  pod 'lottie-ios'
  #pod 'Firebase/Core'
  #pod 'Firebase/Firestore'
  #pod 'Firebase/Storage'
  #pod 'FirebaseUI'
  
  
  pod 'Firebase/Crashlytics'

  pod 'Firebase/Analytics'
  
  pod 'Google-Mobile-Ads-SDK'
  
  
end
